## GET all blogs

GET http://localhost:3000/api/v1/blogs?offset=0

### GET one blog

GET http://localhost:3000/api/v1/blogs/b3b7dc78-23cb-451c-85d5-1d6841b270d8

### ADD a new blog

POST http://localhost:3000/api/v1/blogs
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjMzZTJmMDE5LTdkZWMtNDJjMy1iMDg5LTVjMjcyOGQ1YjM4MiIsImlhdCI6MTcxMjI0ODU3MiwiZXhwIjoxNzEyMjUyMTcyfQ.150PToncs6tyjbnl4Plluz94jQc1zffpm2mk1gbgAzI

{
  "title": "This blog is added through API 22",
  "content": "I am writing this blog through REST API"
}

### UPDATE a blog

PATCH http://localhost:3000/api/v1/blogs/b3b7dc78-23cb-451c-85d5-1d6841b270d8
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjMzZTJmMDE5LTdkZWMtNDJjMy1iMDg5LTVjMjcyOGQ1YjM4MiIsImlhdCI6MTcxMjI0ODU3MiwiZXhwIjoxNzEyMjUyMTcyfQ.150PToncs6tyjbnl4Plluz94jQc1zffpm2mk1gbgAzI

{
  "title": "I have changed the title through REST API"
}

### DELETE a blog

DELETE http://localhost:3000/api/v1/blogs/b3b7dc78-23cb-451c-85d5-1d6841b270d8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjMzZTJmMDE5LTdkZWMtNDJjMy1iMDg5LTVjMjcyOGQ1YjM4MiIsImlhdCI6MTcxMjI0ODU3MiwiZXhwIjoxNzEyMjUyMTcyfQ.150PToncs6tyjbnl4Plluz94jQc1zffpm2mk1gbgAzI